refactor test for handling different supports on SDKs
appwrite/sdk-generator pull request #303
Opened 2021-11-02 10:06 UTC by lohanidamodar

2021-11-02 10:08 UTC, TorstenDittmann approved these changes

2021-11-02 10:14 UTC, abnegate requested changes
Looks good just another `supportException` and test override to remove :+1:

2021-11-02 10:14 UTC, abnegate commented on tests/SDKTest.php
>              'supportException' => true,
```suggestion
```

2021-11-02 10:14 UTC, abnegate commented on tests/SDKTest.php
> +        $whitelist = ['flutter'];
```suggestion
```

2021-11-02 10:16 UTC, abnegate approved these changes

2021-11-04 11:49 UTC, TorstenDittmann approved these changes

2021-11-04 11:49 UTC, merged