Feat swift large file
appwrite/sdk-generator pull request #359
Opened 2022-02-04 09:52 UTC by abnegate

2022-02-07 11:47 UTC, lohanidamodar requested changes
Great work @abnegate, just few comments.

2022-02-07 11:47 UTC, lohanidamodar commented on templates/swift/Sources/Client.swift.twig
> +                        completion(.failure(AppwriteError(
Remove Hardcoded Appwrite

2022-02-07 11:47 UTC, lohanidamodar commented on templates/swift/Sources/Client.swift.twig
> +        completion: ((Result<T, AppwriteError>) -> Void)? = nil
Remove hardcoded appwrite

2022-02-08 06:24 UTC, abnegate commented on tests/SDKTest.php
> +                'swift-5.5' => 'docker run --rm -v $(pwd):/app -w /app/tests/sdks/swift-server swiftarm/swift:5.5.2-focal-multi-arch swift test',
@lohanidamodar This image supports arm64 as well as amd64 so tests can also run locally on M1 Macs

2022-02-08 11:08 UTC, lohanidamodar approved these changes
Looks good to me.

2022-02-09 10:50 UTC, christyjacob4 commented on templates/swift/Sources/Client.swift.twig
> +            headers["x-appwrite-id"] = result["$id"] as? String
If you could replace this string with the value from the spec, it would be great 👍

2022-02-09 10:51 UTC, christyjacob4 approved these changes
Just a minor suggestion

2022-02-11 05:21 UTC, merged