Feat swift async await
appwrite/sdk-generator pull request #409
Opened 2022-03-18 08:23 UTC by abnegate

- Add async/await support for client/service methods
- Defer existing methods to async versions and deprecate completion handler functions

2022-03-21 06:53 UTC, lohanidamodar requested changes
@abnegate let's update the doc examples as well to use async/await

2022-03-21 10:04 UTC, abnegate commented
@lohanidamodar Update docs and integrated examples

2022-03-21 12:11 UTC, christyjacob4 approved these changes

2022-03-23 01:14 UTC, lohanidamodar approved these changes

2022-03-23 05:25 UTC, merged