Flutter/Dart Input file improvements
appwrite/sdk-generator pull request #451
Opened 2022-05-24 08:24 UTC by lohanidamodar

2022-06-07 21:23 UTC, abnegate approved these changes
Looks good to me 👍

2022-06-14 07:21 UTC, Meldiron requested changes

2022-06-14 07:21 UTC, Meldiron commented on templates/flutter/lib/src/input_file.dart.twig
> +  factory InputFile.fromBytes(
In JS I tried to support multiple more, can we do the same in all languages? https://github.com/appwrite/sdk-generator/pull/459/files#diff-ca7384a18814afcd9ae2c2d771382d64ddbec1ee5a19f5272bc664a96fcbeee0R10-R38

2022-06-21 07:06 UTC, Meldiron approved these changes
LGTM

2022-06-21 07:50 UTC, merged