Feat: More options for deno file upload
appwrite/sdk-generator pull request #468
Opened 2022-06-24 10:34 UTC by Meldiron

2022-06-24 12:02 UTC, TorstenDittmann commented
Let's get some second 👀 on this as well

2022-06-27 08:23 UTC, lohanidamodar requested changes
Looks good. Small change and also may be we should add test for buffer, stream and plaintext?

2022-06-27 08:23 UTC, lohanidamodar commented on templates/deno/src/services/service.ts.twig
> +            payload['{{ parameter.name }}'] = { type: 'file', file: new File([uploadableChunkTrimmed], {{ parameter.name | caseCamel | escapeKeyword }}.name), filename: {{ parameter.name | caseCamel
```suggestion
            payload['{{ parameter.name }}'] = { type: 'file', file: new File([uploadableChunkTrimmed], {{ parameter.name | caseCamel | escapeKeyword }}.name), filename: {{ parameter.name | caseCamel | escapeKeyword }}.filename };
```

2022-06-28 00:18 UTC, lohanidamodar commented
@Meldiron Also needs sync

2022-06-28 10:12 UTC, Meldiron commented on templates/deno/src/services/service.ts.twig
> +            payload['{{ parameter.name }}'] = { type: 'file', file: new File([uploadableChunkTrimmed], {{ parameter.name | caseCamel | escapeKeyword }}.name), filename: {{ parameter.name | caseCamel
Renamed to filename

2022-06-28 11:15 UTC, merged