Quality of life updates
appwrite/sdk-generator pull request #503
Opened 2022-08-03 04:01 UTC by abnegate

- Add PHPCS formatter + composer scripts
- Update to PHP 8
- Remove redundant minify params
- Covered by existing tests

2022-08-04 04:51 UTC, lohanidamodar requested changes
Well, this doesn't change anything with the functionality right? these are only housekeeping updates?

Also, let's update travis to run lint.

2022-08-04 23:40 UTC, abnegate commented
@lohanidamodar Yep no functional changes. Added lint to travis as well 👍

2022-10-21 01:00 UTC, lohanidamodar approved these changes
Just to be clear these are only formatting and QOL changes. Looks good.

2022-10-21 07:16 UTC, christyjacob4 commented on src/SDK/Language/Flutter.php
> +                'minify'        => false,
Let's remove the `minify` key from here too

2022-10-21 07:49 UTC, christyjacob4 approved these changes

2022-10-21 20:18 UTC, merged