Feat: Add path keyword
appwrite/sdk-generator pull request #614
Opened 2023-02-15 13:07 UTC by Meldiron

## What does this PR do?

We use `path` as variable name inside function. Such parameter cannot be provided, otherwise there will be an error like

```ts
src/services/functions.ts:583:17 - error TS2300: Duplicate identifier 'path'.

583             let path = '/functions/{functionId}/executions'.replace('{functionId}', functionId);
                    ~~~~
```

## Test Plan

- [x] QA with branch that needs path parameter

## Related PRs and Issues

x

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2023-03-07 02:43 UTC, lohanidamodar commented on src/SDK/Language/Dart.php
> +            "path"
Not a keyword for Dart language

2023-03-07 02:44 UTC, lohanidamodar requested changes
@Meldiron Please add it to only relevant languages and also add it to ` abstract public function getIdentifierOverrides(): array;` or the relevant language to give it a proper replacement like `urlPath` or similar.

2023-03-07 16:15 UTC, Meldiron commented
Converting to draft. Will become relevant again near internal Functions G4 testing

2023-05-11 20:31 UTC, Meldiron commented
<img width="732" alt="CleanShot 2023-05-11 at 22 30 06@2x" src="https://github.com/appwrite/sdk-generator/assets/19310830/55e6cf88-d68d-478d-a132-f49aeb5c977b">

Should be good for now 😅

2023-06-07 06:40 UTC, lohanidamodar commented
@Meldiron can you also add this to identifier overrides so that we can have a override sucha as `filePath` or something instead of the default `xpath` when the keyword arises?
https://github.com/appwrite/sdk-generator/blob/3bd342fbfa771d573fbf877af8ec977e5c7e9194/src/SDK/Language/Dart.php#LL115C8-L115C8

2023-07-18 06:46 UTC, lohanidamodar approved these changes
this is good to merge, my last comment as I discussed with matej, as path can refer to file path, code path or something else, there is no proper identifier override that we can manually do so `xpath` is okay for now

2023-07-18 06:47 UTC, merged