Upgrade dependencies Flutter and dart
appwrite/sdk-generator pull request #661
Opened 2023-05-30 18:36 UTC by 2002Bishwajeet

## What does this PR do?

Upgrade dependencies of Flutter and Dart to make it Dart 3.0 Ready

## Test Plan

Manual QA

## Related PRs and Issues

Fixes [#5583](https://github.com/appwrite/appwrite/issues/5583)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2023-06-04 01:25 UTC, lohanidamodar commented on templates/dart/pubspec.yaml.twig
> +  http: '>=0.13.5 <1.0.1'
```suggestion
  http: '>=0.13.6 <1.0.1'
```

2023-06-04 01:25 UTC, lohanidamodar commented on templates/flutter/pubspec.yaml.twig
> +  http: '>=0.13.5 <1.0.1'
```suggestion
  http: '>=0.13.6 <1.0.1'
```

2023-06-04 01:27 UTC, lohanidamodar commented
@2002Bishwajeet looks good, couple of suggestions and make sure tests are passing.

2023-06-04 10:49 UTC, 2002Bishwajeet commented
@lohanidamodar, The tests that failed doesn't seem related to my changes?

2023-06-05 00:57 UTC, lohanidamodar requested changes
some packages have updated since.

2023-06-05 00:57 UTC, lohanidamodar commented on templates/flutter/pubspec.yaml.twig
>    path_provider: ^2.0.14
```suggestion
  path_provider: ^2.0.15
```

2023-06-05 00:57 UTC, lohanidamodar commented on templates/flutter/pubspec.yaml.twig
> +  universal_html: ^2.2.2
```suggestion
  universal_html: ^2.2.3
```

2023-06-05 00:57 UTC, lohanidamodar commented on templates/flutter/pubspec.yaml.twig
> +  cookie_jar: ^4.0.2
```suggestion
  cookie_jar: ^4.0.3
```

2023-06-06 00:53 UTC, lohanidamodar approved these changes

2023-06-06 00:54 UTC, merged