Flutter SDK: tests for services
appwrite/sdk-generator pull request #673
Opened 2023-06-19 06:52 UTC by lohanidamodar

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2023-06-20 17:08 UTC, stnguyen90 requested changes

2023-06-20 17:08 UTC, stnguyen90 commented on templates/flutter/test/services/service_test.dart.twig
> +                {{parameter.name | escapeKeyword | caseCamel}}: {% if parameter.type == 'object' %}{}{% elseif parameter.type == 'file' %}InputFile.fromPath(path: './image.png'){% else %}'{{parameter
This needs to include a `{% elseif parameter.type == 'array' %}[]` or else the teams_test.dart will fail:

<img width="684" alt="image" src="https://github.com/appwrite/sdk-generator/assets/1477010/4e3b3140-2843-4597-8339-b9e80d5670d3">

```suggestion
                {{parameter.name | escapeKeyword | caseCamel}}: {% if parameter.type == 'object' %}{}{% elseif parameter.type == 'array' %}[]{% elseif parameter.type == 'file' %}InputFile.fromPath(path: './image.png'){% else %}'{{parameter.example}}'{%~ endif ~%},{%~ endfor ~%}
```

2023-06-20 17:12 UTC, stnguyen90 commented
Also, mockito should be added to the pubspec.yaml, right?

2023-06-20 23:46 UTC, lohanidamodar commented
> Also, mockito should be added to the pubspec.yaml, right?

should be added, I must have added, if not feel free to add

2023-06-21 00:55 UTC, stnguyen90 commented on templates/dart/test/src/exception_test.dart.twig
> +import 'package:{{lang.params.packageName}}/src/exception.dart';
```suggestion
import 'package:{{ language.params.packageName }}/src/exception.dart';
```

2023-06-21 00:56 UTC, stnguyen90 commented on templates/dart/test/src/exception_test.dart.twig
> +import 'package:flutter_test/flutter_test.dart';
To make this work in dart and flutter this should be:

```suggestion
{% if 'dart' in language.params.packageName %}
import 'package:test/test.dart';
{% else %}
import 'package:flutter_test/flutter_test.dart';
{% endif %}
```

2023-06-21 01:17 UTC, stnguyen90 approved these changes

2023-06-21 08:09 UTC, merged