Generate Appwrite ID's on the Client-Side
appwrite/sdk-generator pull request #779
Opened 2024-03-05 15:16 UTC by PineappleIOnic

## What does this PR do?

This PR Implements Appwrite's ID generation onto the Client/Server side SDKs

## Test Plan
Existing tests have been modified to check these ID's are being generated and do not match `unique()` anymore.

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2024-03-06 09:10 UTC, gewenyu99 requested changes

2024-03-06 09:10 UTC, gewenyu99 commented on templates/android/library/src/main/java/io/appwrite/ID.kt.twig
> +fun uniqid(): String {
This function just generates a timestamp so our IDs are in order, no?

2024-03-06 09:22 UTC, PineappleIOnic commented on templates/dart/lib/id.dart.twig
> +  // Generate a unique ID based on timestamp
Sure

2024-03-06 18:00 UTC, gewenyu99 requested changes

2024-03-06 18:00 UTC, gewenyu99 commented on templates/ruby/lib/container/id.rb.twig
> +def uniqueId
use snake case

2024-03-06 18:00 UTC, gewenyu99 commented on templates/android/library/src/main/java/io/appwrite/ID.kt.twig
> +private fun uniqueId(): String {
should be called hex timestamp

2024-03-06 18:00 UTC, gewenyu99 commented on templates/android/library/src/main/java/io/appwrite/ID.kt.twig
> +// Generate a unique ID based on timestamp
This is wrong.

2024-03-06 21:20 UTC, gewenyu99 requested changes

2024-03-06 21:20 UTC, gewenyu99 commented on templates/node/lib/id.js.twig
> +        const hexTimestamp = secondsSinceEpoch.toString(16) + microsecondsPart.toString(16).padStart(5, '0');
This line is too long.

2024-03-06 21:20 UTC, gewenyu99 commented on templates/web/src/id.ts.twig
> +function hexTimestamp(): string {
Move this into the class as a private.

2024-03-06 21:20 UTC, gewenyu99 commented on templates/web/src/id.ts.twig
> +  const hexTimestamp = `${secondsSinceEpoch.toString(16)}${microsecondsPart.toString(16).padStart(5, '0')}`;
Break this up into multiple lines.

2024-03-06 21:20 UTC, gewenyu99 commented on templates/swift/Sources/ID.swift.twig
> +func hexTimestamp() -> String {
Make this private and move it in.

2024-03-06 21:20 UTC, gewenyu99 commented on templates/swift/Sources/ID.swift.twig
> +    let microsecondsPart = Int((now.timeIntervalSince1970 - Double(secondsSinceEpoch)) * 1_000_000)
Cna this reference the secondsSinceEpoch part? Not sure. 

secondsSinceEpoch - Double(secondsSinceEpoch)


It's weird that you call a `now.timeIntervalSince1970` twice

2024-03-06 21:20 UTC, gewenyu99 commented on templates/ruby/lib/container/id.rb.twig
> +def hex_timestamp
Private, move this into the class.

2024-03-06 21:20 UTC, gewenyu99 commented on templates/python/package/id.py.twig
> +        random_padding = ''.join(random.choice('0123456789abcdef') for _ in range(padding))
Use 
```py
random_bytes = os.urandom(6)
hex_string = random_bytes.hex()` or something.
```

2024-03-07 18:31 UTC, gewenyu99 requested changes

2024-03-07 18:31 UTC, gewenyu99 commented on templates/deno/src/id.ts.twig
> +        const microsecondsPart = msecs * 1000; // Convert milliseconds to microseconds
Why don't we go to this directly like you do in: `    final msecs = now.microsecondsSinceEpoch - secondsSinceEpoch * 1000000;`

2024-03-07 18:31 UTC, gewenyu99 commented on templates/dotnet/src/Appwrite/ID.cs.twig
> +            var microsecondsPart = (long)(msecs * 1000); // Convert milliseconds to microseconds
Why don't you go directly like:     final msecs = now.microsecondsSinceEpoch - secondsSinceEpoch * 1000000;

2024-03-07 18:31 UTC, gewenyu99 commented on templates/ruby/lib/container/id.rb.twig
> +        def self.hex_timestamp
> You can use private_class_method :method_name if you want to define a class method as private

2024-03-07 18:31 UTC, gewenyu99 commented on templates/web/src/id.ts.twig
> +        const microsecondsPart = now.getMilliseconds() * 1000; // Convert milliseconds to microseconds
Should this not be 
```suggestion
        const microsecondsPart = now.getMilliseconds() * 1000000; // Convert milliseconds to microseconds
```

2024-03-10 14:44 UTC, gewenyu99 commented on templates/android/library/src/main/java/io/package/ID.kt.twig
> +import java.time.Instant
This works good

2024-03-10 14:44 UTC, gewenyu99 commented on templates/dart/lib/id.dart.twig
> +  static String _hexTimestamp() {
Seems to work, I think the timestamp behavior here is a little different from Kotlin.

2024-03-10 14:44 UTC, gewenyu99 commented on templates/deno/src/id.ts.twig
> +        const now = new Date();
Seems to work, but some of the IDs aren't ordered, the timestamp bit is the same.

2024-03-10 14:44 UTC, gewenyu99 commented on templates/dotnet/src/Appwrite/ID.cs.twig
>  namespace {{ spec.title | caseUcfirst }}
Works reliably

2024-03-10 14:44 UTC, gewenyu99 commented on templates/kotlin/src/main/kotlin/io/appwrite/ID.kt.twig
>  package {{ sdk.namespace | caseDot }}
Good

2024-03-10 14:44 UTC, gewenyu99 commented on templates/node/lib/id.js.twig
>  class ID {
Has the padding issues.

2024-03-10 14:44 UTC, gewenyu99 commented on templates/php/src/ID.php.twig
>  namespace {{ spec.title | caseUcfirst }};
Perfect

2024-03-10 14:44 UTC, gewenyu99 commented on templates/python/package/id.py.twig
> +from datetime import datetime
Padding issues.

2024-03-10 14:44 UTC, gewenyu99 commented on templates/ruby/lib/container/id.rb.twig
> +require 'securerandom'
Works well

2024-03-10 16:39 UTC, gewenyu99 approved these changes

2024-03-10 16:52 UTC, eldadfux approved these changes

2024-03-10 16:53 UTC, merged