Fix variable names and logging in web and react-native docs templates #8328
appwrite/sdk-generator pull request #890
Opened 2024-06-27 09:33 UTC by kunalArya1

# Title: Fix Console Logging in Storage Client Example Templates

## Description:
This PR addresses an issue in the example templates for the Appwrite documentation where the console logging of API responses was incorrectly referencing the response variable instead of the result variable. This discrepancy could potentially confuse users following the examples.

## Changes Made:

Updated the console logging in the example templates for both the web and React Native clients to use the result variable consistently.

### Context:
The original templates incorrectly used response in the console.log statement, which does not align with the variable naming conventions in the example code provided. By changing this to result, we ensure clarity and accuracy in the displayed examples.

## Contributor Note:
This change aligns with the conventions observed throughout the documentation examples and improves the usability for developers integrating the Appwrite storage client in their applications.

### References:

Fixes: https://github.com/appwrite/appwrite/issues/8328

### Issue Link

* https://github.com/appwrite/appwrite/issues/8328)

This PR is ready for review. Your feedback is appreciated!

2024-07-08 05:56 UTC, lohanidamodar requested changes
Let's remove comments

2024-07-08 05:56 UTC, lohanidamodar commented on templates/react-native/docs/example.md.twig
> +{# console.log({% if method.type == 'location' %}result{% else %}response{% endif %}); #} //previous code
```suggestion
```

2024-07-08 05:56 UTC, lohanidamodar commented on templates/web/docs/example.md.twig
> +{# console.log({% if method.type == 'location' %}result{% else %}response{% endif %}); #} // previous code
```suggestion
```

2024-07-08 05:56 UTC, lohanidamodar commented on templates/react-native/docs/example.md.twig
> +console.log(result); // Updated to log the result variable
```suggestion
console.log(result);
```

2024-07-08 05:56 UTC, lohanidamodar commented on templates/web/docs/example.md.twig
> +console.log(result); // Updated to log the result variable
```suggestion
console.log(result);
```

2024-07-19 23:36 UTC, stnguyen90 requested changes

2024-07-19 23:36 UTC, stnguyen90 commented on templates/web/docs/example.md.twig
> +{% if method.type != 'webAuth' %}
```suggestion
{% if method.type != 'webAuth' %}
```

2024-07-23 17:45 UTC, choir27 requested changes

2024-08-05 13:44 UTC, choir27 approved these changes

2024-08-05 13:45 UTC, choir27 commented
After pulling your forked branch and generating the examples, I was able to confirm that your branch does generate the correct logging for web and react-native docs

![Screenshot 2024-08-05 094302](https://github.com/user-attachments/assets/c61a978e-fc77-4548-a029-dae9305ea75e)

2024-08-06 00:38 UTC, stnguyen90 approved these changes

2024-08-06 00:51 UTC, merged