Fix chunk uploads
appwrite/sdk-generator pull request #993
Opened 2024-10-02 19:20 UTC by byawitz

## What does this PR do?

Fix chunk uploads with predefined ID for
- Kotlin (android)
- Ruby

## Test Plan

Running these code snippets.
### Kotlin
```kotlin
val client = Client()
    .setEndpoint("https://cloud.appwrite.io/v1") // Your API Endpoint
    .setProject("...")
    .setKey("...");

val s = Storage(client)
val response = s.createFile(
    bucketId = "...",
    fileId = ID.unique(),
    file = InputFile.fromPath("aaa.mp4"),
)
```

### Ruby
```ruby
client = Client.new
               .set_endpoint('https://cloud.appwrite.io/v1') # Your API Endpoint
               .set_project('...') # Your project ID
               .set_key('...') # The user session to authenticate with

storage = Storage.new(client)

result = storage.create_file(
  bucket_id: '...',
  file_id: ID.unique,
  file: InputFile.from_path('aaa.mp4'),
)
```
`aaa.mp4` is bigger than 10MB.

## Related PRs and Issues

#963 

### Have you read the [Contributing Guidelines on issues]
Yes

2024-10-03 00:37 UTC, stnguyen90 reviewed
can we rely on the error type instead of the error message?

2024-10-04 11:28 UTC, loks0n requested changes

2024-10-04 11:28 UTC, loks0n commented on templates/android/library/src/main/java/io/package/Client.kt.twig
> +                if (e.message != null && !e.message!!.contains("file could not be found")) {
Agree with Steven, this seems fragile...

2024-10-04 11:28 UTC, loks0n commented on templates/android/library/src/main/java/io/package/Client.kt.twig
> +                    throw e
Doesn't `call()` methods already throw these exceptions, is there any need to catch and throw here?

2024-10-04 11:28 UTC, loks0n commented on templates/ruby/lib/container/client.rb.twig
>              when nil   then ''
Unrelated, but can we fix the spacing here? Looks weird

2024-10-04 11:28 UTC, loks0n commented on templates/android/library/src/main/java/io/package/Client.kt.twig
> +                val chunksUploaded = current["chunksUploaded"] as Long
Is `Long` type the best choice?

2026-06-11 07:41 UTC, closed without merging